
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: backend-apis
    group: backend
  name: backend-apis
  namespace: prod-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: backend-apis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: backend-apis
      name: backend-apis
    spec:
      containers:
        - image: cr.registryname.com/backend-team/backend-apis:#IMAGE_VERSION#
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/secert/creds.json
          imagePullPolicy: IfNotPresent
          name: backend-apis
          resources: {}
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          ports:
          - containerPort: 1000
            name: grpc
            protocol: TCP
          - containerPort: 2112
            name: http
            protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: prod-cr
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: backend-apis
    group: backend    
  name: backend-apis
  namespace: prod-backend
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: grpc
    port: 1000
    protocol: TCP
    targetPort: 1000
  - name: http
    port: 2112
    protocol: TCP
    targetPort: 2112
  selector:
    k8s-app: backend-apis
  sessionAffinity: None
  type: LoadBalancer