alias(
    name = "grpc_go",
    actual = "@@gazelle~~go_deps~org_golang_google_grpc//:go_default_library",
    visibility = [
        "//visibility:public",
    ],
)

alias(
    name = "grpc_reflection",
    actual = "@@gazelle~~go_deps~org_golang_google_grpc//reflection:go_default_library",
    visibility = ["//visibility:public"],
)

alias(
    name = "prometheus_promhttp",
    actual = "@@gazelle~~go_deps~com_github_prometheus_client_golang//prometheus/promhttp:go_default_library",
    visibility = ["//visibility:public"],
)

alias(
    name = "google_cloud_spanner",
    actual = "@@gazelle~~go_deps~com_google_cloud_go_spanner//:go_default_library",
    visibility = ["//visibility:public"],
)

alias(
    name = "prometheus",
    actual = "@@gazelle~~go_deps~com_github_prometheus_client_golang//prometheus:go_default_library",
    visibility = ["//visibility:public"],
)

alias(
    name = "google_cloud_secretmanager",
    actual = "@@gazelle~~go_deps~com_google_cloud_go_secretmanager//apiv1:go_default_library",
    visibility = ["//visibility:public"],
)

alias(
    name = "google_cloud_secretmanager_pb",
    actual = "@@gazelle~~go_deps~com_google_cloud_go_secretmanager//apiv1/secretmanagerpb:go_default_library",
    visibility = ["//visibility:public"],
)

alias(
    name = "google_api_iterator",
    actual = "@@gazelle~~go_deps~org_golang_google_api//iterator:go_default_library",
    visibility = ["//visibility:public"],
)
